### ISSUE TITLE
TreeController.dispose  iconButton

### ISSUE THREAD

**Issue by hellobq** [chrisr04/flutter_simple_treeview#1]
hello, i have two questions for you
first, should the treeController be destroyed when the page is destroyed?
and then, how can I change the size of iconbutton? thanks. look forward to your reply.

**Comment by chrisr04** [comment]
Hi, answering your questions:
1. there's no need, the treeController doesn't have a method to dispose it.
2. for change the size of iconButton, here is an example using `Transform.scale` widget:
```
Transform.scale(
  scale: 0.7,
  child: IconButton(
    iconSize: widget.iconSize ?? 24.0,
    icon: Icon(icon, color: Colors.white),
    onPressed: onIconPressed,
  ),
)
```
I hope I've helped

**Comment by hellobq** [comment]
> Hi, answering your questions:
> 
> 1. there's no need, the treeController doesn't have a method to dispose it.
> 2. for change the size of iconButton, here is an example using `Transform.scale` widget:
> 
> ```
> Transform.scale(
>   scale: 0.7,
>   child: IconButton(
>     iconSize: widget.iconSize ?? 24.0,
>     icon: Icon(icon, color: Colors.white),
>     onPressed: onIconPressed,
>   ),
> )
> ```
> 
> I hope I've helped

it seems that i have to copy the library and modify it. emmm,  can't receive dynamic parameters? like Size.big、Size.middle、and Size.small.
